# [dbo].[EmployeeDetails]

In [ ]:
/****** Object:  Table [dbo].[EmployeeDetails]    Script Date: 6/16/2024 9:31:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeDetails](
	[Emp_Id] [int] NOT NULL,
	[Emp_Name] [nvarchar](200) NOT NULL,
	[Company_Name] [nvarchar](500) NOT NULL,
	[Verification_Code] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Emp_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

In [ ]:
INSERT [dbo].[EmployeeDetails] ([Emp_Id], [Emp_Name], [Company_Name], [Verification_Code]) VALUES (10001, N'Rajaneesh_NET', N'Cisive', N'100XZ')
INSERT [dbo].[EmployeeDetails] ([Emp_Id], [Emp_Name], [Company_Name], [Verification_Code]) VALUES (10002, N'Neena_HR', N'Cisive', N'100XZ')
INSERT [dbo].[EmployeeDetails] ([Emp_Id], [Emp_Name], [Company_Name], [Verification_Code]) VALUES (10003, N'TestUser1', N'Test_Comp', N'100XZ')
INSERT [dbo].[EmployeeDetails] ([Emp_Id], [Emp_Name], [Company_Name], [Verification_Code]) VALUES (10004, N'TestUser2', N'Test_Comp1', N'100XZ')
GO

# [dbo].[sp_EmploymentVerification]

In [ ]:
/****** Object:  StoredProcedure [dbo].[sp_EmploymentVerification]    Script Date: 6/16/2024 9:31:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[sp_EmploymentVerification]
(
@Emp_Id int,
@Company_Name nvarchar(500),
@Verification_Code nvarchar(500) 
)
as 
begin 
declare @isVerified varchar(50)=null
if exists (select 1 from EmployeeDetails where Emp_Id=@Emp_Id and Company_Name=@Company_Name and Verification_Code=@Verification_Code)
	begin 
		set @isVerified='Verified'  
	end 
else 
	begin
		set @isVerified='Not Verified'  
	end 

	select @isVerified as isVerified
end 

--exec [sp_EmploymentVerification] 10001,'Cisive','100XZ'
GO

# [dbo].[sp_GetEmployeeList]

In [ ]:
/****** Object:  StoredProcedure [dbo].[sp_GetEmployeeList]    Script Date: 6/16/2024 9:31:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[sp_GetEmployeeList]

as 
begin 

select 
	Emp_Id,
	Emp_Name,
	Company_Name,
	Verification_Code from EmployeeDetails
	
end 
GO